In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [ ]:
# Basics

import numpy as np

a = np.array([1,2,3], dtype='int16')
print(a)

b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[1 2 3]
[[9. 8. 7.]
 [6. 5. 4.]]


In [14]:
# Get Dimensions
print(a.ndim)
print(b.ndim)

# Get Shape
print(a.shape)
print(b.shape)

# Get Type
print(a.dtype)
print(b.dtype)

# Get Size
print(a.itemsize)
print(b.itemsize)

# Get Total Size
print(a.nbytes)
print(b.nbytes)

1
2
(3,)
(2, 3)
int16
float64
2
8
6
48


In [24]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])

# Get a specific element [r,c]
print(a[1,5])
print(a[0,-1])

# Get a specific row
print(a[0,:])

# Get a specific column
print(a[:,2])

# Getting fancy [startindex:endindex:stepsize]
print(a[0,1:6:2])

# Changing an element
a[1,5] = 20
print(a)

# Changing an entire row
a[0,:] = 100
print(a)

13
7
[1 2 3 4 5 6 7]
[ 3 10]
[2 4 6]
[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]
[[100 100 100 100 100 100 100]
 [  8   9  10  11  12  20  14]]


In [28]:
# 3D Arrays
b = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

# Get specific element (work outside in)
print(b[0,1,1])
print(b[:,1,:])

# Replace
b[:,1,:] = [[9,9],[8,8]]

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
4
[[3 4]
 [7 8]]


In [41]:
# INITIALIZING DIFFERENT TYPES OF ARRAYS

# All 0s matrix
a = np.zeros((2,3))
print(a)

# All 1s matrix
a = np.ones((4,2,2), dtype='int16')
print(a)

# Any other number
a = np.full((2,2), 99)
print(a)

# Any other number (full_like)
b = np.array([[1,2,3],[4,5,6]])
a = np.full_like(b, 4)
print(a)

# Random decimal numbers
a = np.random.rand(4,2)
print(a)

# Random integer values
a = np.random.randint(-4,8,size=(3,3))
print(a)

# Identity matrix
a = np.eye(5)
print(a)

[[0. 0. 0.]
 [0. 0. 0.]]
[[[1 1]
  [1 1]]

 [[1 1]
  [1 1]]

 [[1 1]
  [1 1]]

 [[1 1]
  [1 1]]]
[[99 99]
 [99 99]]
[[4 4 4]
 [4 4 4]]
[[0.22019543 0.83232393]
 [0.65346687 0.70683378]
 [0.76076478 0.63996472]
 [0.75045925 0.71818046]]
[[ 6  7  5]
 [-3  0 -4]
 [-1  1  1]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [47]:
# Repeat an array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr, 3, axis=0)
print(r1)

# Harder
output = np.ones((5,5))
output[1:-1,1:-1] = np.zeros((3,3))
output[2,2] = 9
print(output)

# Copying Arrays Wrong Way
a = np.array([1,2,3])
b = a  # b is just a reference to a
b[0] = 100
print(a)  # a is also changed

# Copying Arrays the Right Way
a = np.array([1,2,3])
b = a.copy()  # b is a copy of a
b[0] = 100
print(a)  # a is NOT changed

[[1 2 3]
 [1 2 3]
 [1 2 3]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]
[100   2   3]
[1 2 3]


In [51]:
# MATHEMATICS

a = np.array([1,2,3,4])
b = np.array([5,6,7,8])

# Arithmetic
print(a - 2)
print(a * 2)
print(a + b)
print(a ** 2)
print(np.sin(a))

[-1  0  1  2]
[2 4 6 8]
[ 6  8 10 12]
[ 1  4  9 16]
[ 0.84147098  0.90929743  0.14112001 -0.7568025 ]


In [53]:
# LINEAR ALGEBRA

# Matrix Multiplication
a = np.ones((2,3))
b = np.full((3,2), 2)
print(np.matmul(a,b))

# Find the Determinant
a = np.array([[1,2],[3,4]])
print(np.linalg.det(a))

[[6. 6.]
 [6. 6.]]
-2.0000000000000004


In [56]:
# STATISTICS

stats = np.array([[1,2,3],[4,5,6]])
print(np.min(stats))
print(np.max(stats, axis=1))
print(np.sum(stats))
print(np.mean(stats))
print(np.median(stats))
print(np.corrcoef(stats))

1
[3 6]
21
3.5
3.5
[[1. 1.]
 [1. 1.]]


In [60]:
# REORGANIZING ARRAYS

before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)
after = before.reshape((4,2))
print(after)

# Vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])
v3 = np.array([9,10,11,12])
print(np.vstack([v1,v2,v3]))

# Horizontally stacking vectors
h1 = np.ones((2,4))
h2 = np.zeros((2,2))
print(np.hstack((h1,h2)))

[[1 2 3 4]
 [5 6 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[1. 1. 1. 1. 0. 0.]
 [1. 1. 1. 1. 0. 0.]]


In [78]:
# MISCELLANEOUS

filedata = np.genfromtxt('data.txt', delimiter=',')
filedata = filedata.astype('int32')
print(filedata)

# Boolean Masking & Advanced Indexing
print(filedata > 50)
print(filedata[filedata > 50])

a = np.array([1,2,3,4,5,6,7,8,9])
print(a[[1,3,5]])

print(np.any(filedata > 50, axis=0))
print(np.all(filedata > 50, axis=0))
print(np.any((filedata > 50) & (filedata < 100), axis=1))

[[  1  13  21  11 196  75   4   3  34   6   7   8   0   1   2   3   4   5]
 [  3  42  12  33 766  75   4  55   6   4   3   4   5   6   7   0  11  12]
 [  1  22  33  11 999  11   2   1  78   0   1   2   9   8   7   1  76  88]]
[[False False False False  True  True False False False False False False
  False False False False False False]
 [False False False False  True  True False  True False False False False
  False False False False False False]
 [False False False False  True False False False  True False False False
  False False False False  True  True]]
[196  75 766  75  55 999  78  76  88]
[2 4 6]
[False False False False  True  True False  True  True False False False
 False False False False  True  True]
[False False False False  True False False False False False False False
 False False False False False False]
[ True  True  True]


In [98]:
# Advanced Problems

a = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],
              [16,17,18,19,20],[21,22,23,24,25],[26,27,28,29,30]])

print(a[2:4,0:2])
for i in range(a.shape[0]-2):
    print(a[i,i+1])
print(a[[0,1,2,3],[1,2,3,4]])

print(a[[0,4,5],3:])

[[11 12]
 [16 17]]
2
8
14
20
[ 2  8 14 20]
[[ 4  5]
 [24 25]
 [29 30]]
